### ISSUE TITLE
windows vm can not detect gpu device？ 

### ISSUE THREAD

**Issue by silenceper** [NVIDIA/kubevirt-gpu-device-plugin#25]
Use this device plugin to successfully start a windows vm, and the GPU can be seen in the device manager, but the GPU cannot be detected through the `Geek3D GPU Caps viewer` software. In the `CUDA` and `Open CL` options, the GPU can be seen？

![image](https://user-images.githubusercontent.com/2044558/128834929-9ce11fa0-a1f8-4135-9085-c62676fe363d.png)

![image](https://user-images.githubusercontent.com/2044558/128835195-a1ddb3f8-2658-4be3-9846-ec000bacec75.png)

**Comment by rthallisey** [comment]
Are you using the latest gpu-dp `nvcr.io/nvidia/kubevirt-gpu-device-plugin:v1.0.1` ?  This sounds like it was fixed in https://github.com/NVIDIA/kubevirt-gpu-device-plugin/pull/22

**Comment by silenceper** [comment]
@rthallisey I try update image from to `v1.0.1`, But the problem is not solved.

**Comment by rthallisey** [comment]
Can you post the yaml from a node that should have the GPU on it?  Also, can you post the logs form the gpu device plugin?

**Comment by silenceper** [comment]
The problem has been solved, it is caused by the lack of gpu driver
